#!/bin/sh
#

UMLGRAPH_HOME=.

if [ x$2 = x ]
then
	echo usage: umlgraph base_file_name filetype [umlgraph arguments] 1>&2
	echo example: umlgraph MyClass png 1>&2
	echo '(The above will convert MyClass.java into MyClass.png)' 1>&2
	exit 1
else
	BASE=$1
	FILETYPE=$2
	shift 2
	java -classpath "$UMLGRAPH_HOME/UmlGraph.jar:$JAVA_HOME/lib/tools.jar" \
	org.umlgraph.doclet.UmlGraph -package $* -output - $BASE.java |
	dot -T$FILETYPE -o$BASE.$FILETYPE
fi
