# We'll manage this visually.
Layout/LineLength:
  Enabled: false

# We'll follow RubyMine indentation layout.
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented
  IndentationWidth: 2

# Nope.
Style/FrozenStringLiteralComment:
  Enabled: false

# We'll just use double quotes everywhere.
Style/StringLiterals:
  EnforcedStyle: double_quotes

# I prefer not to use %i or %I for an array of symbols.
Style/SymbolArray:
  Enabled: false

# We are not going to optimize by freezing strings.
Style/MutableConstant:
  Enabled: false
